### ISSUE TITLE
remove quarantine from all msdial files from terminal

### ISSUE THREAD

**Issue by ethanbass** [Jiung-Wen/msdial#2]
nice guide! For the mac installation, you can disable the quarantine from the command line instead of clicking through all the security error messages in the System Preferences panel. 

```
sudo xattr -r -d com.apple.quarantine ./MSDIAL_ver.4.80_OSX/*
```

**Comment by Jiung-Wen** [comment]
Thank you for this elegant way! I have added this to the tutorial!
JC
